# -*- coding: utf-8 -*-
"""DEProject_team2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXCFoR7XNXjkSRwFi-dmUqGEO8b6Z-qF
"""

from pathlib import Path
import pandas as pd



input = Path("/content/team_2.parquet")
output = Path("output/partitioned_dataset")


df = pd.read_parquet(input)

print("\nDataset loaded successfully.")
print(f"Rows: {len(df)}")
print(f"Columns: {len(df.columns)}")

print("\nColumns:")
print(df.columns.tolist())

print("\nPreview:")
print(df.head())


# =========================================================
# FIND DATE COLUMN
# =========================================================

date_column = "timestamp"

# =========================================================
# CONVERT TO DATETIME
# =========================================================

df[date_column] = pd.to_datetime(df[date_column])

# =========================================================
# CREATE PARTITION COLUMNS
# =========================================================

df["year"] = df[date_column].dt.year
df["month"] = df[date_column].dt.month
df["day"] = df[date_column].dt.day


# =========================================================
# WRITE PARTITIONED DATASET
# =========================================================

print("\nWriting partitioned parquet dataset...")

df.to_parquet(
    output,
    engine="pyarrow",
    partition_cols=["year", "month", "day"],
    index=False
)

print("\nDone.")
print(f"Partitioned dataset written to: {output.resolve()}")

!pip install duckdb -q

import os

# Find the parquet file and partitioned output
for root, dirs, files in os.walk('/content'):
    for f in files:
        if f.endswith('.parquet'):
            full = os.path.join(root, f)
            size = os.path.getsize(full)
            print(f"{full}  →  {size:,} bytes")

import pandas as pd

df = pd.read_parquet('/content/team_2.parquet')
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print(df.head(3))

import duckdb

con = duckdb.connect()

result = con.execute("""
    SELECT
        DAY(timestamp::TIMESTAMPTZ)   AS day,
        COUNT(*)                      AS event_count
    FROM read_parquet('/content/team_2.parquet')
    WHERE YEAR(timestamp::TIMESTAMPTZ)  = 2024
      AND MONTH(timestamp::TIMESTAMPTZ) = 7
    GROUP BY 1
    ORDER BY 1
""").df()

print(result)

result = con.execute("""
    SUMMARIZE SELECT * FROM read_parquet('/content/team_2.parquet')
""").df()

print(result)

con = duckdb.connect('/content/team_2.duckdb')

con.execute("""
    CREATE TABLE IF NOT EXISTS events AS
    SELECT *, timestamp::TIMESTAMPTZ AS ts
    FROM read_parquet('/content/team_2.parquet')
""")

print("Table saved. Row count:")
print(con.execute("SELECT COUNT(*) FROM events").df())

import duckdb

con = duckdb.connect()

result = con.execute("""
    SUMMARIZE SELECT * FROM read_parquet('/content/team_2.parquet')
""").df()

print(result[['column_name', 'column_type', 'min', 'max', 'null_percentage']])

import duckdb

con = duckdb.connect('/content/air_quality.duckdb')

con.execute("""
    CREATE TABLE IF NOT EXISTS dim_station (
        station_id   VARCHAR PRIMARY KEY,
        station_name VARCHAR,
        city         VARCHAR,
        state        VARCHAR
    );

    CREATE TABLE IF NOT EXISTS dim_pollutant (
        pollutant_id   VARCHAR PRIMARY KEY,
        pollutant_name VARCHAR,
        unit           VARCHAR DEFAULT 'ug/m3'
    );

    CREATE TABLE IF NOT EXISTS dim_date (
        date_id  INTEGER PRIMARY KEY,
        year     INTEGER,
        month    INTEGER,
        day      INTEGER,
        hour     INTEGER,
        datetime TIMESTAMPTZ
    );

    CREATE TABLE IF NOT EXISTS fact_measurements (
        measurement_id BIGINT PRIMARY KEY,
        station_id     VARCHAR REFERENCES dim_station(station_id),
        pollutant_id   VARCHAR REFERENCES dim_pollutant(pollutant_id),
        date_id        INTEGER REFERENCES dim_date(date_id),
        value          DOUBLE,
        at_c           DOUBLE,
        rh_percent     DOUBLE,
        ws_m_s         DOUBLE,
        wd_deg         DOUBLE,
        rf_mm          DOUBLE,
        sr_w_mt2       DOUBLE,
        bp_mmhg        DOUBLE,
        vws_m_s        DOUBLE
    );
""")

print("Tables created.")

# dim_station — unique stations
con.execute("""
    INSERT OR IGNORE INTO dim_station
    SELECT DISTINCT station_id, station_name, city, state
    FROM read_parquet('/content/team_2.parquet');
""")

# dim_pollutant — unique pollutants
con.execute("""
    INSERT OR IGNORE INTO dim_pollutant (pollutant_id, pollutant_name)
    SELECT DISTINCT pollutant, pollutant
    FROM read_parquet('/content/team_2.parquet')
    WHERE pollutant IS NOT NULL;
""")

# dim_date — use epoch seconds as unique ID
con.execute("""
    INSERT OR IGNORE INTO dim_date
    SELECT DISTINCT
        CAST(EPOCH(timestamp::TIMESTAMPTZ) AS INTEGER) AS date_id,
        year, month, day, hour,
        timestamp::TIMESTAMPTZ AS datetime
    FROM read_parquet('/content/team_2.parquet');
""")

# fact_measurements — all readings
con.execute("""
    INSERT OR IGNORE INTO fact_measurements
    SELECT
        ROW_NUMBER() OVER ()                               AS measurement_id,
        station_id,
        pollutant                                          AS pollutant_id,
        CAST(EPOCH(timestamp::TIMESTAMPTZ) AS INTEGER)     AS date_id,
        value, at_c, rh_percent, ws_m_s, wd_deg,
        rf_mm, sr_w_mt2, bp_mmhg, vws_m_s
    FROM read_parquet('/content/team_2.parquet');
""")

print("Data loaded.")

for table in ['dim_station', 'dim_pollutant', 'dim_date', 'fact_measurements']:
    count = con.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
    print(f"{table}: {count:,} rows")

result = con.execute("""
    SELECT
        s.city,
        p.pollutant_name,
        d.year,
        d.month,
        ROUND(AVG(f.value), 2) AS avg_value,
        ROUND(MAX(f.value), 2) AS max_value
    FROM fact_measurements f
    JOIN dim_station  s ON f.station_id   = s.station_id
    JOIN dim_pollutant p ON f.pollutant_id = p.pollutant_id
    JOIN dim_date      d ON f.date_id      = d.date_id
    GROUP BY s.city, p.pollutant_name, d.year, d.month
    ORDER BY d.year, d.month, s.city
    LIMIT 20
""").df()

print(result)